name = "yt-dl-worker"
main = "src/index.js"
compatibility_date = "2026-09-01"
account_id = "cc4668baab24a44ebe315a3807279d15"

[vars]
WORKER_URL = "https://yt-dl-worker.vivekpereiraalbert.workers.dev"

[observability]
enabled = true

[[kv_namespaces]]
binding = "PROBES"
id = "7bc9f25243e64844a4c82e6a74adaf33"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.client.js"]
fallthrough = true
